package id.dana.sendmoney.ui.globalsend.form.mapper;

import id.dana.sendmoney.domain.globalsend.model.validate.BeneficiaryInfo;
import id.dana.sendmoney.ui.globalsend.form.model.BeneficiaryInfoModel;
import kotlin.Metadata;
import kotlin.jvm.internal.Intrinsics;

@Metadata(d1 = {"\u0000\f\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\u001a\u0011\u0010\u0002\u001a\u00020\u0001*\u00020\u0000¢\u0006\u0004\b\u0002\u0010\u0003\u001a\u0011\u0010\u0002\u001a\u00020\u0000*\u00020\u0001¢\u0006\u0004\b\u0002\u0010\u0004"}, d2 = {"Lid/dana/sendmoney/ui/globalsend/form/model/BeneficiaryInfoModel;", "Lid/dana/sendmoney/domain/globalsend/model/validate/BeneficiaryInfo;", "BuiltInFictitiousFunctionClassFactory", "(Lid/dana/sendmoney/ui/globalsend/form/model/BeneficiaryInfoModel;)Lid/dana/sendmoney/domain/globalsend/model/validate/BeneficiaryInfo;", "(Lid/dana/sendmoney/domain/globalsend/model/validate/BeneficiaryInfo;)Lid/dana/sendmoney/ui/globalsend/form/model/BeneficiaryInfoModel;"}, k = 2, mv = {1, 6, 0}, xi = 48)
/* loaded from: classes5.dex */
public final class BeneficiaryModelMapperKt {
    public static final BeneficiaryInfo BuiltInFictitiousFunctionClassFactory(BeneficiaryInfoModel beneficiaryInfoModel) {
        Intrinsics.checkNotNullParameter(beneficiaryInfoModel, "");
        return new BeneficiaryInfo(beneficiaryInfoModel.MyBillsEntityDataFactory, beneficiaryInfoModel.NetworkUserEntityData$$ExternalSyntheticLambda2, beneficiaryInfoModel.NetworkUserEntityData$$ExternalSyntheticLambda8, beneficiaryInfoModel.scheduleImpl, beneficiaryInfoModel.PlaceComponentResult, beneficiaryInfoModel.lookAheadTest, beneficiaryInfoModel.NetworkUserEntityData$$ExternalSyntheticLambda6, beneficiaryInfoModel.getErrorConfigVersion, beneficiaryInfoModel.NetworkUserEntityData$$ExternalSyntheticLambda3, beneficiaryInfoModel.FragmentBottomSheetPaymentSettingBinding, beneficiaryInfoModel.BuiltInFictitiousFunctionClassFactory, beneficiaryInfoModel.getAuthRequestContext, beneficiaryInfoModel.NetworkUserEntityData$$ExternalSyntheticLambda0, beneficiaryInfoModel.NetworkUserEntityData$$ExternalSyntheticLambda7, beneficiaryInfoModel.GetContactSyncConfig, beneficiaryInfoModel.KClassImpl$Data$declaredNonStaticMembers$2, beneficiaryInfoModel.NetworkUserEntityData$$ExternalSyntheticLambda4, beneficiaryInfoModel.initRecordTimeStamp, beneficiaryInfoModel.isLayoutRequested, beneficiaryInfoModel.newProxyInstance, beneficiaryInfoModel.PrepareContext, beneficiaryInfoModel.getCallingPid, beneficiaryInfoModel.moveToNextValue, beneficiaryInfoModel.DatabaseTableConfigUtil, beneficiaryInfoModel.NetworkUserEntityData$$ExternalSyntheticLambda1, beneficiaryInfoModel.whenAvailable, beneficiaryInfoModel.NetworkUserEntityData$$ExternalSyntheticLambda5);
    }

    public static final BeneficiaryInfoModel BuiltInFictitiousFunctionClassFactory(BeneficiaryInfo beneficiaryInfo) {
        Intrinsics.checkNotNullParameter(beneficiaryInfo, "");
        return new BeneficiaryInfoModel(beneficiaryInfo.BuiltInFictitiousFunctionClassFactory, beneficiaryInfo.initRecordTimeStamp, beneficiaryInfo.NetworkUserEntityData$$ExternalSyntheticLambda7, beneficiaryInfo.lookAheadTest, beneficiaryInfo.MyBillsEntityDataFactory, beneficiaryInfo.NetworkUserEntityData$$ExternalSyntheticLambda0, beneficiaryInfo.NetworkUserEntityData$$ExternalSyntheticLambda3, beneficiaryInfo.moveToNextValue, beneficiaryInfo.FragmentBottomSheetPaymentSettingBinding, beneficiaryInfo.NetworkUserEntityData$$ExternalSyntheticLambda6, beneficiaryInfo.KClassImpl$Data$declaredNonStaticMembers$2, beneficiaryInfo.getAuthRequestContext, beneficiaryInfo.scheduleImpl, beneficiaryInfo.newProxyInstance, beneficiaryInfo.NetworkUserEntityData$$ExternalSyntheticLambda1, beneficiaryInfo.PlaceComponentResult, beneficiaryInfo.NetworkUserEntityData$$ExternalSyntheticLambda4, beneficiaryInfo.GetContactSyncConfig, beneficiaryInfo.isLayoutRequested, beneficiaryInfo.PrepareContext, beneficiaryInfo.NetworkUserEntityData$$ExternalSyntheticLambda8, beneficiaryInfo.getCallingPid, beneficiaryInfo.getErrorConfigVersion, beneficiaryInfo.DatabaseTableConfigUtil, beneficiaryInfo.NetworkUserEntityData$$ExternalSyntheticLambda2, beneficiaryInfo.readMicros, beneficiaryInfo.NetworkUserEntityData$$ExternalSyntheticLambda5);
    }
}
