package com.airbnb.lottie;

import android.graphics.Bitmap;
import android.graphics.ColorFilter;
import android.graphics.PointF;
import android.graphics.Typeface;
import com.airbnb.lottie.value.ScaleXY;

/* loaded from: classes6.dex */
public interface LottieProperty {
    public static final Typeface AppCompatEmojiTextHelper;
    public static final Float BottomSheetCardBindingView$watcherCardNumberView$1;
    public static final ColorFilter BuiltInFictitiousFunctionClassFactory;
    public static final Float C;
    public static final Float D;
    public static final Integer[] DatabaseTableConfigUtil;
    public static final Float E;
    public static final Float KClassImpl$Data$declaredNonStaticMembers$2;
    public static final Float MyBillsEntityDataFactory;
    public static final Float NetworkUserEntityData$$ExternalSyntheticLambda0;
    public static final Float NetworkUserEntityData$$ExternalSyntheticLambda1;
    public static final Bitmap NetworkUserEntityData$$ExternalSyntheticLambda2;
    public static final Float NetworkUserEntityData$$ExternalSyntheticLambda3;
    public static final Float NetworkUserEntityData$$ExternalSyntheticLambda4;
    public static final Float NetworkUserEntityData$$ExternalSyntheticLambda5;
    public static final PointF NetworkUserEntityData$$ExternalSyntheticLambda6;
    public static final Float NetworkUserEntityData$$ExternalSyntheticLambda7;
    public static final PointF NetworkUserEntityData$$ExternalSyntheticLambda8;
    public static final Float PrepareContext;
    public static final Float SubSequence;
    public static final Float VerifyPinStateManager$executeRiskChallenge$2$1;
    public static final Float VerifyPinStateManager$executeRiskChallenge$2$2;
    public static final CharSequence getCallingPid;
    public static final Float getErrorConfigVersion;
    public static final ScaleXY getOnBoardingScenario;
    public static final Float getSupportButtonTintMode;
    public static final Float getValueOfTouchPositionAbsolute;
    public static final Float initRecordTimeStamp;
    public static final Float isLayoutRequested;
    public static final Float lookAheadTest;
    public static final Float moveToNextValue;
    public static final Float newProxyInstance;
    public static final Float readMicros;
    public static final PointF scheduleImpl;
    public static final Integer getAuthRequestContext = 1;
    public static final Integer FragmentBottomSheetPaymentSettingBinding = 2;
    public static final Integer B = 3;
    public static final Integer GetContactSyncConfig = 4;
    public static final Integer PlaceComponentResult = 5;
    public static final PointF whenAvailable = new PointF();
    public static final PointF A = new PointF();

    static {
        Float valueOf = Float.valueOf(15.0f);
        C = valueOf;
        Float valueOf2 = Float.valueOf(16.0f);
        BottomSheetCardBindingView$watcherCardNumberView$1 = valueOf2;
        Float valueOf3 = Float.valueOf(17.0f);
        MyBillsEntityDataFactory = valueOf3;
        scheduleImpl = new PointF();
        NetworkUserEntityData$$ExternalSyntheticLambda6 = new PointF();
        Float valueOf4 = Float.valueOf(0.0f);
        KClassImpl$Data$declaredNonStaticMembers$2 = valueOf4;
        NetworkUserEntityData$$ExternalSyntheticLambda8 = new PointF();
        getOnBoardingScenario = new ScaleXY();
        VerifyPinStateManager$executeRiskChallenge$2$2 = Float.valueOf(1.0f);
        E = valueOf4;
        D = valueOf4;
        NetworkUserEntityData$$ExternalSyntheticLambda4 = Float.valueOf(2.0f);
        readMicros = Float.valueOf(3.0f);
        NetworkUserEntityData$$ExternalSyntheticLambda5 = Float.valueOf(4.0f);
        NetworkUserEntityData$$ExternalSyntheticLambda3 = Float.valueOf(5.0f);
        PrepareContext = Float.valueOf(6.0f);
        NetworkUserEntityData$$ExternalSyntheticLambda7 = Float.valueOf(7.0f);
        initRecordTimeStamp = Float.valueOf(8.0f);
        newProxyInstance = Float.valueOf(9.0f);
        NetworkUserEntityData$$ExternalSyntheticLambda1 = Float.valueOf(10.0f);
        isLayoutRequested = Float.valueOf(11.0f);
        getValueOfTouchPositionAbsolute = Float.valueOf(12.0f);
        VerifyPinStateManager$executeRiskChallenge$2$1 = Float.valueOf(12.1f);
        getSupportButtonTintMode = Float.valueOf(13.0f);
        SubSequence = Float.valueOf(14.0f);
        moveToNextValue = valueOf;
        NetworkUserEntityData$$ExternalSyntheticLambda0 = valueOf2;
        lookAheadTest = valueOf3;
        getErrorConfigVersion = Float.valueOf(18.0f);
        BuiltInFictitiousFunctionClassFactory = new ColorFilter();
        DatabaseTableConfigUtil = new Integer[0];
        AppCompatEmojiTextHelper = Typeface.DEFAULT;
        NetworkUserEntityData$$ExternalSyntheticLambda2 = Bitmap.createBitmap(1, 1, Bitmap.Config.ALPHA_8);
        getCallingPid = "dynamic_text";
    }
}
